name: generate svg

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install nwdiag
        run: |
          python -m pip install --upgrade pip
          pip install nwdiag
      - name: generate svg
        run: nwdiag -T svg *.yml
      - name: save artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: '*.svg'
